### ISSUE TITLE
xml dump broken due to problem with ID

### ISSUE THREAD

**Issue by emiltin** [iampersistent/OSMlib-base#1]
looks like it's fixed in the repo, but the fix is not included in the gem that gets installed.

see https://github.com/IamPersistent/OSMlib-base/commit/3302f17efcac3c75598df4c6e9c7788d455719a9

**Comment by iampersistent** [comment]
I'm not really maintaining this, I just don't have the time. I'd be more than happy to pass this off to someone and I'll definitely merge any PRs

**Comment by emiltin** [comment]
thanks for replying. in fact it's already fixed in your code, it's just that the fix somehow is not propagated to the gem.

**Comment by emiltin** [comment]
outdated
